version: 1.6.{build}
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
- cmd: powershell -file build.ps1 -localDotNet -buildNumber %APPVEYOR_BUILD_NUMBER%
artifacts:
- path: nodenative\dist\*.tgz
  name: nodepackage
- path: nodenative\dist-electron\*.tgz
  name: electronpackage
- path: coreclrnode\bin\Release\*.nupkg
  name: nugetpackage